### ISSUE TITLE
Quick fix and Subtype property problems 

### ISSUE THREAD

**Issue by msomp** [365businessdev/vscode-alxmldocumentation#23]
While reviewing and testing the changes for #18 and #21 I found two more issues, probably:

1. The quick fix / add documentation action inserts the doc template, but cuts out the first character of the method name
2. when generating the markdown documentation for a codeunit with a Subtype property, an error occurs: Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by sirhc101** [comment]
Hello @msomp 

thank you for reporting the issues.
Unfortunately I was not able to reproduce the problems with my test objects.

Could you pls provide an example and the call stack of the exception?

Thank you very much.

**Comment by sirhc101** [comment]
If`ve tested in some more projects and found one where an similar error occured. The documentation is inserted after 'p' of 'procedure'. Pretty strange to be honest, I look into it more deeply but need some example anyway.

Thank you in advance.

**Comment by msomp** [comment]
Hi,

in the screenshot there's an example of what's happening when I insert a documentation for a procedure with the quick fix function:
![Bildschirmfoto 2020-07-29 um 08 36 48](https://user-images.githubusercontent.com/55102386/88765371-adc5f800-d176-11ea-80d1-524f3948ba64.jpg)

Additionally, please find a simple Install Codeunit attached where the exception occurs at my side. The output is:

`AL XML Documentation version 0.4.2
Copyright (C) 365 business development. All rights reserved

Markdown export started for 'c:\NAV\AL\N2S ECM Interface\App\Src\codeunit\N2SInstall.Codeunit copy.al' at '08:32:53'

An error occurred while processing:
Error: Command failed: "c:\Users\Martin\.vscode\extensions\365businessdevelopment.bdev-al-xml-doc-0.4.2/bin/ALCodeCommentMarkdownCreator.exe"  -g -o "c:\NAV\AL\N2S ECM Interface\App\doc" -f "c:\NAV\AL\N2S ECM Interface\App\Src\codeunit\N2SInstall.Codeunit copy.al"
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at ALCodeCommentMarkdownCreator.SourceFile.GenerateIndex() in C:\DevOps\365businessdev.ALCodeCommentMarkdownCreator\ALCodeCommentMarkdownCreator\SourceFile.cs:line 273
   at ALCodeCommentMarkdownCreator.SourceFile.GenerateMarkdown() in C:\DevOps\365businessdev.ALCodeCommentMarkdownCreator\ALCodeCommentMarkdownCreator\SourceFile.cs:line 266
   at ALCodeCommentMarkdownCreator.Program.ProcessSourceFiles(String inputDirectory, String inputFile, String outputDirectory, Boolean verbose, Boolean globalOnly) in C:\DevOps\365businessdev.ALCodeCommentMarkdownCreator\ALCodeCommentMarkdownCreator\Program.cs:line 109
   at ALCodeCommentMarkdownCreator.Program.Process(CmdOptions opts) in C:\DevOps\365businessdev.ALCodeCommentMarkdownCreator\ALCodeCommentMarkdownCreator\Program.cs:line 64
   at ALCodeCommentMarkdownCreator.Program.<>c.<Main>b__0_0(CmdOptions opts) in C:\DevOps\365businessdev.ALCodeCommentMarkdownCreator\ALCodeCommentMarkdownCreator\Program.cs:line 26
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at ALCodeCommentMarkdownCreator.Program.Main(String[] args) in C:\DevOps\365businessdev.ALCodeCommentMarkdownCreator\ALCodeCommentMarkdownCreator\Program.cs:line 25
`
[N2SInstallDocTest.Codeunit.al.zip](https://github.com/365businessdev/vscode-alxmldocumentation/files/4993082/N2SInstallDocTest.Codeunit.al.zip)

I found out that this always seems to happen, when any kind of subtype is specified. When removing the subtype line, everything works like a charm.

Thanks, Martin.

**Comment by sirhc101** [comment]
Thank you very much! I fixed it and published the new version 0.4.3 with the bugfixes.

**Comment by msomp** [comment]
Thank your for the quick fix!
